### ISSUE TITLE
Build with static libxml++3

### ISSUE THREAD

**Issue by spvkgn** [loskutov/deadbeef-lyricbar#12]
Is it possible to build against `libxml++-3.0.a` ? If distro not contains libxml++3 package, I guess it would be useful just to build against static libxml++3.

**Comment by loskutov** [comment]
The Makefile doesn't intend to support every possible way to build a library from the sources; however, now you can add linker flags via `LDFLAGS`.

Actually, nothing forces libxml++ to be linked dynamically, except default settings. The only actual requirement is that pkg-config gives the correct flags. The simplest way to achieve that is usually to build a package, which is the intended way for installing software in modern Linux distributions, so I don't see any problem here.

**Comment by dakeryas** [comment]
Спасибо за `LDFLAGS`!
