### ISSUE TITLE
Random Gio::ResolverError  exception crashes

### ISSUE THREAD

**Issue by dakeryas** [loskutov/deadbeef-lyricbar#14]
For reasons I cannot figure out yet (internet connexion or other), an exception seems to be throw randomly in `fetch_file`, I suggest at least wrapping the `Gio::File` instantiation in a `try / catch` block instead of having DeaDBeeF terminate:

```
experimental::optional<std::string> fetch_file(const std::string &uri) {

try{
    auto gfile = Gio::File::create_for_uri(uri);
    auto stream = gfile->read();
  //...
}
catch(std::exception& e){
    std::cerr<<"Failed fetching file from "<<uri<<"\n";
    return {};
}

}
```

**Comment by loskutov** [comment]
Fixed.
