### ISSUE TITLE
Problem With Make

### ISSUE THREAD

**Issue by NorbertoAlexander** [loskutov/deadbeef-lyricbar#18]
Hello.

I've been trying to install this plug since night but the Make keeps giving me this error, I tried creating the folder deadbeef/deadbee.h in usr/lib but also doesn't work. My version of deadbeef installs on /opt/deadbeef/bin/deadbeef 

There is any way to change the direction where the output from the make is created so I can move manually the file to the plugin folder? Thanks

g++ src/ui.cpp -c `pkg-config --cflags libxml++-3.0 gtkmm-3.0 gtk+-3.0` -std=c++17 -Wall -O2 -fPIC -fvisibility=hidden -flto
In file included from src/ui.cpp:1:0:
src/ui.h:5:10: fatal error: deadbeef/deadbeef.h: No such file or directory
 #include <deadbeef/deadbeef.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:24: recipe for target 'ui.o' failed
make: *** [ui.o] Error 1

**Comment by loskutov** [comment]
Your installation must include the `deadbeef/deadbeef.h` header file. If it's located in some non-standard path (e.g. /opt/deadbeef/include/deadbeef/deadbeef), try running make with additional compiler flags (`CFLAGS='-I/opt/deadbeef/include' CXXFLAGS='-I/opt/deadbeef/include' make`).

**Comment by NorbertoAlexander** [comment]
Thank you. There was no way I could find out about that by myself.
