### ISSUE TITLE
Lyricbar interferes with the user interface of other plugins

### ISSUE THREAD

**Issue by MarcRdC** [loskutov/deadbeef-lyricbar#19]
When the Lyricbar plugin is installed, the configuration window of some other plugins lacks some or all elements. See this [issue](https://github.com/DeaDBeeF-Player/deadbeef/issues/2360) on DeaDBeef repository for details.

**Comment by AsVHEn** [comment]
I saw it's `setlocale(LC_ALL, "");` fault.
https://github.com/loskutov/deadbeef-lyricbar/issues/30#issue-974592343
