### ISSUE TITLE
[Question] - Possible to Make like Infobar?

### ISSUE THREAD

**Issue by 0pLuS0** [loskutov/deadbeef-lyricbar#21]
Hello,

Do you think it could be possible to make this like Infobar, Bio and Lyrics to work with the latest Deadbeef?

https://bitbucket.org/dsimbiriatin/deadbeef-infobar/wiki/Home

THANKS

**Comment by loskutov** [comment]
If you want a slightly improved version of infobar, check https://bitbucket.org/IgnatLoskutov/deadbeef-infobar-ng/.
As of lyricbar, it's intended to be simple, so it's unlikely to ever feature stuff like Bio.

**Comment by 0pLuS0** [comment]
Infobar-ng does not work with the latest version of Deadbeef, that is why I made this reques, seeing your last development was earlier that that project, hoping to reach someone here on Github to revive either one of them to work with the latest deadbeef.

THANKS
