### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by securearth** [loskutov/deadbeef-lyricbar#24]
Deadbeef supports Window. While I use both Windows and Linux, I need installation instructions for Windows, as installing such things is very easy on gnu/linux.
Windows installation instructions will help more people

**Comment by loskutov** [comment]
I think it should possible but not that easy. However, only GNU/Linux systems are currently [poorly] supported, so I'd recommend sticking to foobar2000 under Windows—AFAIK it has a plenty of nice plugins.
