### ISSUE TITLE
Installation on Fedora 34

### ISSUE THREAD

**Issue by ghost** [loskutov/deadbeef-lyricbar#26]
Does someone successfully installed this plugin on Fedora? The dependencies instructions refers only for a .deb based distro and seems those deps aren't available in Fedora repos.

**Comment by rootsandculture** [comment]
I found the dependencies `dnf install gtkmm30-devel libxml++30-devel` in Fedora 34. Copied the `deadbeef.h` to the source folder and run `make gtk3` but something is wrong. 

`g++ src/ui.cpp -c `pkg-config --cflags libxml++-3.0 gtkmm-3.0 gtk+-3.0` -std=c++14 -Wall -O2 -fPIC -fvisibility=hidden -flto
/bin/sh: line 1: g++: command not found
make: *** [Makefile:25: ui.o] Error 127
`

**Comment by loskutov** [comment]
I guess what you need instead of copying files is the `deadbeef-devel` package from RPM Fusion / UnitedRPMs.
