### ISSUE TITLE
cc1plus: error: /usr/lib/libxml++-3.0/include: Permission denied

### ISSUE THREAD

**Issue by gitbobo** [loskutov/deadbeef-lyricbar#27]
As deadbeef.h locate in `/opt/deadbeef/include/deadbeef/deadbeef.h`,I install plugin as below:  

`sudo apt install checkinstall && wget http://ftp.gnome.org/pub/GNOME/sources/libxml++/3.0/libxml++-3.0.1.tar.xz && tar -xJf libxml++-3.0.1.tar.xz && cd libxml++-3.0.1 && env CFLAGS='-I/opt/deadbeef/include' CXXFLAGS='-I/opt/deadbeef/include' ./configure --prefix=/usr && make && sudo make install`

#`cc1plus: error: /usr/lib/libxml++-3.0/include: Permission denied` occured
```
me@pc:~/deadbeef-lyricbar$ make gtk3
g++ src/ui.cpp -c `pkg-config --cflags libxml++-3.0 gtkmm-3.0 gtk+-3.0` -std=c++14 -Wall -O2 -fPIC -fvisibility=hidden -flto
cc1plus: error: /usr/lib/libxml++-3.0/include: Permission denied
make: *** [Makefile:25: ui.o] Error 1
me@pc:~/deadbeef-lyricbar$ CFLAGS='-I/opt/deadbeef/include' CXXFLAGS='-I/opt/deadbeef/include' make gtk3
g++ src/ui.cpp -c `pkg-config --cflags libxml++-3.0 gtkmm-3.0 gtk+-3.0` -I/opt/deadbeef/include -std=c++14 -Wall -O2 -fPIC -fvisibility=hidden -flto
cc1plus: error: /usr/lib/libxml++-3.0/include: Permission denied
make: *** [Makefile:25: ui.o] Error 1
```

**Comment by loskutov** [comment]
The latest version of lyricbar no longer depends on libxml++-3.0.
