### ISSUE TITLE
Отступы для текста

### ISSUE THREAD

**Issue by Alatau** [loskutov/deadbeef-lyricbar#33]
Подскажите, пожалуйста, как сделать так, чтобы при выравнивании текста песни по левой стороне, текст начинался не от границы плеера (сейчас он впритык!), а с отступом, хотя бы процентов на 15 от края приложения. Спасибо большое за ваше расширение для DeadBeef! Я не разбираюсь в программировании, поэтому, к сожалению, не смогу этого сделать самостоятельно.

upd: странным образом отступы вдруг появились, и теперь тексты выглядят эстетично.

**Comment by loskutov** [comment]
Да, добавлено ещё в #16.
