### ISSUE TITLE
Ability to change background/text colors

### ISSUE THREAD

**Issue by DaarkWel** [loskutov/deadbeef-lyricbar#4]
Please add. It looks pretty weird with my color scheme. Like a white bald spot :-)

![](http://storage2.static.itmages.ru/i/17/1217/h_1513529552_4325551_6ec97dc28c.jpg)

**Comment by loskutov** [comment]
I think the problem is caused by your color scheme, which lyricbar totally obeys. For instance, here's what it looks like with the Arc-dark theme:
![Arc-dark sample](http://storage4.static.itmages.ru/i/17/1217/h_1513536683_1377647_9a382eaf4a.png)

**Comment by DaarkWel** [comment]
I meant color scheme of Deadbeef, not GTK theme. I am using gtk2 version and I overrode gtk settings in Deadbeef preferences — Appearance — Playlist (I just need white background and black text in all my other gtk applications, like text editor and browser, but Deadbeef looks better with dark background). Other Deadbeef plugins that I'm using — Waveform Seekbar and Spectrogram — has color settings, but Lyricbar has neither such option nor ability to inherit overriden options from Deadbeef.

**Comment by C0rn3j** [comment]
I have a similar question - how do I change color of partial text in the code? I've been staring at it myself, and figured I should probably be doing something with Pango judging from code like this

```
	tagItalic = refBuffer->create_tag();
	tagItalic->property_style() = Pango::STYLE_ITALIC;
```

But I suck at C/C++ so I can't really figure out what exactly I need to do, having an example would be awesome.

I want to see if I can do something like this - 
![image](https://user-images.githubusercontent.com/1641362/54084692-3ea6f400-4334-11e9-8a6a-1eec31d87c00.png)

**Comment by loskutov** [comment]
@C0rn3j check this: https://developer.gnome.org/gtkmm-tutorial/stable/sec-textview-buffer.html.en#textview-formatting

You need to create a tag to hold the color (the example they have is `refTagMatch->property_background() = "orange"`, foreground is available in a similar manner) and then use `apply_tag` to apply it to a portion of the text. I do something similar inside `set_lyrics`, except I use `insert_with_tags` because formatting is static in my case.

**Comment by C0rn3j** [comment]
I've tried setting both background and foreground to orange as per the example via both ways (applying it to specific text or just adding it directly with the formatting) and neither works.

The text will get added but it'll have the same black color as everything else, do you perhaps see what I'm doing wrong?

![image](https://user-images.githubusercontent.com/1641362/55861644-14389880-5b77-11e9-8b4f-69f65f6f97ce.png)
