### ISSUE TITLE
Center sort by default

### ISSUE THREAD

**Issue by C0rn3j** [loskutov/deadbeef-lyricbar#8]
I'd say the center sort is vastly superior to left/right sorting, but left sorting is the default.

It needs 2 simple number flips. I'd make a PR but I absolutely suck at git, so here's the needed changes if you agree with me.

https://github.com/C0rn3j/deadbeef-lyricbar/commit/050f19f5172ea11ea23326a0dbc52363d8b16dcd

**Comment by loskutov** [comment]
Took your commit, thanks!
