### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mistersister** [loskutov/deadbeef-lyricbar#9]
Hello, 
Im trying to compile the gtk2 plugin from sources but get this error:

```
[cbarrabes@mothership deadbeef-lyricbar-master]$ make gtk2
g++ src/ui.cpp -c `pkg-config --cflags libxml++-3.0 gtkmm-2.4 gtk+-2.0` -std=c++14 -Wall -O2 -fPIC -fvisibility=hidden -flto
In file included from src/ui.cpp:1:
src/ui.h:5:10: fatal error: deadbeef/deadbeef.h: No such file or directory
 #include <deadbeef/deadbeef.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:24: ui.o] Error 1
```

Im using Arch LInux and Deadbeef 1.8.0 with the following dependencies installed:
gtkmm 1:2.24.5-3
gtkmm3 3.24.1-1
libxml++ 3.0.1+4+g2af973f-3
libxml2 2.9.9-2

Any help please?
Thanks!

**Comment by loskutov** [comment]
As far as I can see the Arch official repositories [only feature 0.7.2](https://www.archlinux.org/packages/community/x86_64/deadbeef/) currently. How did you install 1.8.0?

**Comment by mistersister** [comment]
@loskutov , I installed the stable 1.8 static build from Deadbeef official website:

https://sourceforge.net/projects/deadbeef/files/travis/linux/1.8.0/deadbeef-static_1.8.0-1_x86_64.tar.bz2/download

**Comment by loskutov** [comment]
In this case you'll have to provide the paths manually, e.g.:
```sh
CFLAGS='-I/opt/deadbeef/include' CXXFLAGS='-I/opt/deadbeef/include' make gtk3
```

**Comment by mistersister** [comment]
thanks, that worked great and is installed now!
